### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by PeterkalM** [tomudding/Player-Visibility#11]
My console is sometimes spamming this error: http://pastebin.com/raw/sDLyfvCW
I'm using 2.5 plugin version, and don't know what is causing this.

Also you can duplicate slime item when you are in creative mode and middle click on them.

**Comment by tomudding** [comment]
I'll look into it, I don't know what is causing the problem because the line that is causing the error should not cause an error. (and I am busy at the moment, so I cannot solve it immediately). 

You are not supposed to use the toggle item when you are in creative mode, I'll try to implement a method to prevent you from duplicating it, but I think that that is not be possible.

**Comment by tomudding** [comment]
@BlackRavenMC Did you walk on a pressure plate when the error occurred?

**Comment by tomudding** [comment]
I have fixed the error and added some item duplication prevention things for creative inventory but **a server is not in control of what a creative client does**. This means I cannot prevent the double click from happening.

**Comment by tomudding** [comment]
I have fixed the error and added some item duplication prevention things for creative inventory but **a server is not in control of what a creative client does**. This means I cannot prevent the double click from happening.
